### ISSUE TITLE
bundle.js:10831 Uncaught Error: `mapStateToData` 和 `mapDispatchToThis` 必须为函数

### ISSUE THREAD

**Issue by yi** [acurseJ/mp-redux#1]
mapDispatchToThis 应该可以是一个 Object 的吧。 

我看您的示例里面 
```
const mapDispatchToProps = {
    add
}
```

**Comment by yi** [comment]
npm 上的版本貌似不对，您方便重新publish 新版本到npm 上去吗？

**Comment by NightLighting** [comment]
你好，npm上的同名包是另一个人写的，不是我这个repo，如果需要使用的话，可以看README里的使用说明。

**Comment by Drakes-0** [comment]
> npm 上的版本貌似不对，您方便重新publish 新版本到npm 上去吗？

你好，npm上的同名包是另一个人写的，不是我这个repo，如果需要使用的话，可以看README里的使用说明。

**Comment by yi** [comment]
原来如此

我通过 `github:NightLighting/mp-redux` 安装好了。用上了
这是个神器啊。 100万个👍
